import type { Metadata } from "next";
import { Providers } from "@/components/providers";
import "./globals.css";
import TopNav from "@/components/navbar/TopNav";

export const metadata: Metadata = {
  title: "Match me",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TopNav />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
